import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
  },
  logo: {
    width: 80,
    height: 30,
    resizeMode: 'contain',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profilePic: {
    width: 38,
    height: 38,
    borderRadius: 19,
    marginLeft: 15,
    backgroundColor: '#EEE',
    borderWidth: 1,
    borderColor: '#DDD',
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  greetingContainer: {
    marginTop: 10,
    marginBottom: 25,
  },
  greetingText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1A1A1A',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2ECC71',
    marginRight: 8,
  },
  statusText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  essenceCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  essenceLabel: {
    color: '#8E8E93',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 1.2,
    marginBottom: 16,
  },
  essenceQuote: {
    color: '#FFFFFF',
    fontSize: 17,
    lineHeight: 24,
    fontStyle: 'italic',
    fontWeight: '500',
    marginBottom: 24,
  },
  readMoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  readMoreText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 'bold',
    marginRight: 6,
    textDecorationLine: 'underline',
  },
  glutenFreeCard: {
    backgroundColor: '#F2F2F7',
    borderRadius: 20,
    padding: 24,
    flexDirection: 'row',
    marginBottom: 30,
    alignItems: 'flex-start',
  },
  glutenFreeContent: {
    flex: 1,
    paddingRight: 12,
  },
  glutenFreeTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  glutenFreeDescription: {
    fontSize: 14,
    color: '#3A3A3C',
    lineHeight: 20,
    marginBottom: 20,
  },
  glutenFreeBold: {
    fontWeight: '700',
  },
  glutenFreeIconContainer: {
    width: 56,
    height: 56,
    backgroundColor: '#E5E5EA',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#8E8E93',
    letterSpacing: 1.5,
    marginBottom: 16,
    textTransform: 'uppercase',
  },
  toolsContainer: {
    flexDirection: 'row',
  },
  toolCard: {
    backgroundColor: '#FFFFFF',
    width: 110,
    height: 110,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  toolIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F2F2F7',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  toolLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1C1C1E',
  },
});
